/**
 * TDAC Session Manager
 *
 * Manages TDAC session-specific encrypted IDs for form dropdowns.
 * These IDs are dynamically generated by the TDAC system and change per session.
 *
 * IMPORTANT: TDAC uses encrypted/encoded IDs for dropdown options (gender, transport mode,
 * accommodation, purpose, nationality). These IDs are NOT static - they are generated
 * per session and can expire. Hardcoding them will eventually break the submission.
 *
 * IDEAL IMPLEMENTATION (Future):
 * - Initialize TDAC session via API
 * - Fetch dropdown options dynamically
 * - Cache IDs for session duration
 * - Refresh when session expires
 *
 * CURRENT IMPLEMENTATION (Fallback):
 * - Uses last known IDs extracted from HAR files
 * - Provides warning when IDs may be stale
 * - Easy to update when IDs change
 *
 * @module TDACSessionManager
 */

import logger from '../LoggingService';

// Type definitions
interface GenderIds {
  MALE: string;
  FEMALE: string;
  UNDEFINED: string;
}

interface TransportModeIds {
  COMMERCIAL_FLIGHT: string;
  PRIVATE_CARGO: string;
  OTHERS_AIR: string;
  AIR_GENERAL: string;
  LAND_GENERAL: string;
  SEA_GENERAL: string;
  AIR: string;
  LAND: string;
  SEA: string;
  [key: string]: string;
}

interface AccommodationIds {
  HOTEL: string;
  YOUTH_HOSTEL: string;
  GUEST_HOUSE: string;
  FRIEND_HOUSE: string;
  APARTMENT: string;
  OTHERS: string;
  [key: string]: string;
}

interface PurposeIds {
  HOLIDAY: string;
  MEETING: string;
  SPORTS: string;
  BUSINESS: string;
  INCENTIVE: string;
  MEDICAL_WELLNESS: string;
  EDUCATION: string;
  CONVENTION: string;
  EMPLOYMENT: string;
  EXHIBITION: string;
  OTHERS: string;
  [key: string]: string;
}

interface NationalityIds {
  CHN: string;
  HKG: string;
  MAC: string;
  [key: string]: string;
}

interface TDACSessionData {
  sessionId: string;
  genderIds: GenderIds;
  transportModeIds: TransportModeIds;
  accommodationIds: AccommodationIds;
  purposeIds: PurposeIds;
  nationalityIds: NationalityIds;
  fetchedAt: Date;
  expiresAt: Date;
  isDynamic: boolean;
}

interface InitializeOptions {
  forceFresh?: boolean;
  timeout?: number;
}

interface AllOptions {
  genders: string[];
  transportModes: string[];
  accommodations: string[];
  purposes: string[];
  nationalities: string[];
}

class TDACSessionManager {
  private sessionData: TDACSessionData | null = null;
  private sessionId: string | null = null;
  private isInitialized: boolean = false;

  /**
   * Initialize TDAC session and fetch dropdown IDs
   *
   * FUTURE IMPLEMENTATION:
   * 1. Open TDAC page to trigger session creation
   * 2. Handle Cloudflare protection
   * 3. Extract dropdown options from page/API
   * 4. Parse encrypted IDs
   * 5. Cache for session duration
   *
   * CURRENT IMPLEMENTATION:
   * - Uses fallback IDs extracted from HAR files (2024-Q1)
   * - Logs warning about potential staleness
   *
   * @param options - Initialization options
   * @returns Session data with encrypted IDs
   */
  async initialize(options: InitializeOptions = {}): Promise<TDACSessionData> {
    const { forceFresh = false, timeout = 30000 } = options;

    // If already initialized and not forcing fresh, return cached data
    if (this.isInitialized && !forceFresh && this.sessionData) {
      // Check if session is still valid
      if (this.sessionData.expiresAt && new Date() < this.sessionData.expiresAt) {
        logger.info('TDACSessionManager', 'Using cached TDAC session data', { sessionId: this.sessionId });
        return this.sessionData;
      }
    }

    logger.info('TDACSessionManager', 'Initializing TDAC session...');
    logger.warn('TDACSessionManager', 'Using fallback TDAC IDs. These are session-specific and may expire.');
    logger.warn('TDACSessionManager', 'For production, implement dynamic ID fetching from TDAC API.');

    // Use fallback IDs (extracted from HAR files - 2024-Q1)
    this.sessionData = this._getFallbackSessionData();
    this.sessionId = this.sessionData.sessionId;
    this.isInitialized = true;

    logger.info('TDACSessionManager', 'TDAC session initialized (fallback mode)', { sessionId: this.sessionId });
    return this.sessionData;
  }

  /**
   * Get fallback session data with last known IDs
   *
   * These IDs were extracted from HAR files capturing TDAC API calls.
   * They are session-specific and WILL CHANGE when TDAC rotates sessions.
   *
   * To update these IDs:
   * 1. Open TDAC website in browser
   * 2. Open DevTools > Network tab
   * 3. Fill form and capture network requests
   * 4. Find API calls with dropdown data
   * 5. Extract new encrypted IDs
   * 6. Update this method
   *
   * @returns Fallback session data
   * @private
   */
  private _getFallbackSessionData(): TDACSessionData {
    const now = new Date();
    const expiresAt = new Date(now.getTime() + 24 * 60 * 60 * 1000); // 24 hours

    return {
      sessionId: 'fallback-session-' + now.getTime(),
      fetchedAt: now,
      expiresAt: expiresAt,
      isDynamic: false, // Using fallback, not dynamically fetched

      // Gender IDs (extracted 2024-Q1)
      genderIds: {
        MALE: 'g5iW15ADyFWOAxDewREkVA==',
        FEMALE: 'JGb85pWhehCWn5EM6PeL5A==',
        UNDEFINED: 'W6iZt0z/ayaCvyGt6LXKIA==',
      },

      // Transport Mode IDs (extracted 2024-Q1)
      transportModeIds: {
        // Specific modes
        COMMERCIAL_FLIGHT: '6XcrGmsUxFe9ua1gehBv/Q==',
        PRIVATE_CARGO: 'yYdaVPLIpwqddAuVOLDorQ==',
        OTHERS_AIR: 'mhapxYyzDmGnIyuZ0XgD8Q==',

        // General modes
        AIR_GENERAL: 'ZUSsbcDrA+GoD4mQxvf7Ag==',
        LAND_GENERAL: 'roui+vydIOBtjzLaEq6hCg==',
        SEA_GENERAL: 'kFiGEpiBus5ZgYvP6i3CNQ==',

        // Aliases
        AIR: '6XcrGmsUxFe9ua1gehBv/Q==', // Same as COMMERCIAL_FLIGHT
        LAND: 'roui+vydIOBtjzLaEq6hCg==',
        SEA: 'kFiGEpiBus5ZgYvP6i3CNQ==',
      },

      // Accommodation Type IDs (extracted 2024-Q1)
      accommodationIds: {
        HOTEL: 'kSqK152aNAx9HQigxwgnUg==',
        YOUTH_HOSTEL: 'Bsldsb4eRsgtHy+rwxGvyQ==',
        GUEST_HOUSE: 'xyft2pbI953g9FKKER4OZw==',
        FRIEND_HOUSE: 'ze+djQZsddZtZdi37G7mZg==',
        APARTMENT: 'PUB3ud2M4eOVGBmCEe4q2Q==',
        OTHERS: 'lIaJ6Z7teVjIeRF2RT97Hw==',
      },

      // Travel Purpose IDs (extracted 2024-Q1)
      purposeIds: {
        HOLIDAY: 'ZUSsbcDrA+GoD4mQxvf7Ag==',
        MEETING: 'roui+vydIOBtjzLaEq6hCg==',
        SPORTS: 'kFiGEpiBus5ZgYvP6i3CNQ==',
        BUSINESS: '//wEUc0hKyGLuN5vojDBgA==',
        INCENTIVE: 'g3Kfs7hn033IoeTa5VYrKQ==',
        MEDICAL_WELLNESS: 'Khu8eZW5Xt/2dVTwRTc7oA==',
        EDUCATION: '/LDehQQnXbGFGUe2mSC2lw==',
        CONVENTION: 'a7NwNw5YbtyIQQClpkDxiQ==',
        EMPLOYMENT: 'MIIPKOQBf05A/1ueNg8gSA==',
        EXHIBITION: 'DeSHtTxpXJk+XIG5nUlW6w==',
        OTHERS: 'J4Ru2J4RqpnDSHeA0k32PQ==',
      },

      // Nationality IDs (extracted 2024-Q1 - limited sample)
      nationalityIds: {
        CHN: 'n8NVa/feQ+F5Ok859Oywuw==', // China
        HKG: 'g6ud3ID/+b3U95emMTZsBw==', // Hong Kong
        MAC: '6H4SM3pACzdpLaJx/SR7sg==', // Macau
        // TODO: Extract more nationality IDs from HAR files as needed
      },
    };
  }

  /**
   * Get gender ID
   * @param gender - Gender (MALE, FEMALE, UNDEFINED)
   * @returns Encrypted gender ID
   */
  getGenderId(gender: string): string {
    if (!this.isInitialized || !this.sessionData) {
      throw new Error('TDACSessionManager not initialized. Call initialize() first.');
    }

    const normalizedGender = gender?.toUpperCase().trim();
    const id = this.sessionData.genderIds[normalizedGender];

    if (!id) {
      logger.warn('TDACSessionManager', 'Unknown gender', { gender, available: Object.keys(this.sessionData.genderIds) });
      return '';
    }

    return id;
  }

  /**
   * Get transport mode ID
   * @param mode - Transport mode (COMMERCIAL_FLIGHT, AIR, LAND, SEA, etc.)
   * @returns Encrypted transport mode ID
   */
  getTransportModeId(mode: string): string {
    if (!this.isInitialized || !this.sessionData) {
      throw new Error('TDACSessionManager not initialized. Call initialize() first.');
    }

    const normalizedMode = mode?.toUpperCase().trim();
    const id = this.sessionData.transportModeIds[normalizedMode];

    if (!id) {
      logger.warn('TDACSessionManager', 'Unknown transport mode, defaulting to COMMERCIAL_FLIGHT', { mode });
      return this.sessionData.transportModeIds.COMMERCIAL_FLIGHT;
    }

    return id;
  }

  /**
   * Get accommodation type ID
   * @param type - Accommodation type (HOTEL, YOUTH_HOSTEL, etc.)
   * @returns Encrypted accommodation ID
   */
  getAccommodationId(type: string): string {
    if (!this.isInitialized || !this.sessionData) {
      throw new Error('TDACSessionManager not initialized. Call initialize() first.');
    }

    const normalizedType = type?.toUpperCase().trim();
    const id = this.sessionData.accommodationIds[normalizedType];

    if (!id) {
      logger.warn('TDACSessionManager', 'Unknown accommodation type, defaulting to HOTEL', { type });
      return this.sessionData.accommodationIds.HOTEL;
    }

    return id;
  }

  /**
   * Get travel purpose ID
   * @param purpose - Travel purpose (HOLIDAY, BUSINESS, etc.)
   * @returns Encrypted purpose ID
   */
  getPurposeId(purpose: string): string {
    if (!this.isInitialized || !this.sessionData) {
      throw new Error('TDACSessionManager not initialized. Call initialize() first.');
    }

    const normalizedPurpose = purpose?.toUpperCase().trim();
    const id = this.sessionData.purposeIds[normalizedPurpose];

    if (!id) {
      logger.warn('TDACSessionManager', 'Unknown purpose', { purpose, available: Object.keys(this.sessionData.purposeIds) });
      return '';
    }

    return id;
  }

  /**
   * Get nationality ID
   * @param nationality - Nationality code (CHN, HKG, MAC, etc.)
   * @returns Encrypted nationality ID or empty string if not found
   */
  getNationalityId(nationality: string): string {
    if (!this.isInitialized || !this.sessionData) {
      throw new Error('TDACSessionManager not initialized. Call initialize() first.');
    }

    const normalizedNationality = nationality?.toUpperCase().trim();
    const id = this.sessionData.nationalityIds[normalizedNationality];

    if (!id) {
      logger.warn('TDACSessionManager', 'Unknown nationality, may need to extract ID from TDAC HAR file', { nationality });
      return '';
    }

    return id;
  }

  /**
   * Check if session is still valid
   * @returns True if session is valid
   */
  isSessionValid(): boolean {
    if (!this.isInitialized || !this.sessionData) {
      return false;
    }

    if (this.sessionData.expiresAt && new Date() >= this.sessionData.expiresAt) {
      return false;
    }

    return true;
  }

  /**
   * Clear session data and force re-initialization
   */
  clearSession(): void {
    this.sessionData = null;
    this.sessionId = null;
    this.isInitialized = false;
    logger.info('TDACSessionManager', 'TDAC session cleared');
  }

  /**
   * Get all available dropdown options
   * Useful for debugging and UI population
   * @returns All dropdown options
   */
  getAllOptions(): AllOptions {
    if (!this.isInitialized || !this.sessionData) {
      throw new Error('TDACSessionManager not initialized. Call initialize() first.');
    }

    return {
      genders: Object.keys(this.sessionData.genderIds),
      transportModes: Object.keys(this.sessionData.transportModeIds),
      accommodations: Object.keys(this.sessionData.accommodationIds),
      purposes: Object.keys(this.sessionData.purposeIds),
      nationalities: Object.keys(this.sessionData.nationalityIds),
    };
  }
}

// Create singleton instance
const tdacSessionManager = new TDACSessionManager();

export default tdacSessionManager;
export { TDACSessionManager };
export type {
  TDACSessionData,
  InitializeOptions,
  AllOptions,
  GenderIds,
  TransportModeIds,
  AccommodationIds,
  PurposeIds,
  NationalityIds
};

