
/**
 * Styles for TDACWebViewScreen
 *
 * Extracted styles for the TDAC WebView filling assistant screen
 */

import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography, spacing } from '../../theme';

const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    marginLeft: -spacing.sm,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  headerRight: {
    width: 40,
  },
  webView: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    zIndex: 50,
  },
  loadingSpinnerContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.primary + '15',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  loadingPulse: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    opacity: 0.8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  loadingTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  loadingSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  loadingText: {
    fontSize: 16,
    color: colors.textSecondary,
    marginTop: spacing.md,
  },
  loadingProgress: {
    width: SCREEN_WIDTH * 0.7,
    height: 6,
    backgroundColor: colors.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  loadingProgressBar: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 3,
  },
  loadingProgressFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 3,
  },
  visualMaskContainer: {
    flex: 1,
    position: 'relative',
  },
  maskBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    zIndex: 5,
  },
  verificationWindow: {
    position: 'absolute',
    top: SCREEN_HEIGHT * 0.3,
    left: spacing.lg,
    right: spacing.lg,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
    zIndex: 10,
    alignItems: 'center',
  },
  windowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  windowIcon: {
    fontSize: 36,
    marginRight: spacing.sm,
  },
  windowTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  windowSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 4,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  verificationContent: {
    width: '100%',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  verificationPrompt: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    marginBottom: spacing.xs,
    textAlign: 'center',
  },
  verificationPromptEn: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  windowFooter: {
    alignItems: 'center',
  },
  footerText: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  focusArrow: {
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  focusArrowIcon: {
    fontSize: 28,
  },
  backgroundBlur: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
  },
  blurOverlay: {
    flex: 1,
    backgroundColor: 'rgba(245, 245, 245, 0.35)',
  },
  loadingBox: {
    alignItems: 'center',
    padding: spacing.xl,
    borderRadius: 20,
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
    borderWidth: 2,
    borderColor: colors.primary,
    minWidth: 200,
  },
  loadingSubText: {
    marginTop: spacing.xs,
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  cloudflareReminderOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    zIndex: 20,
  },
  cloudflareReminderBox: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.xl,
    marginHorizontal: spacing.lg,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  cloudflareReminderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  cloudflareReminderText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: spacing.xl,
  },
  cloudflareReminderButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    borderRadius: 8,
    minWidth: 120,
  },
  cloudflareReminderButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  visualMask: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    zIndex: 15,
  },
  helper: {
    position: 'absolute',
    bottom: spacing.md,
    right: spacing.md,
    backgroundColor: colors.primary,
    borderRadius: 28,
    padding: spacing.md,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  helperIcon: {
    fontSize: 24,
  },
  helperPanel: {
    position: 'absolute',
    bottom: 80,
    right: spacing.md,
    backgroundColor: colors.white,
    borderRadius: 12,
    width: SCREEN_WIDTH * 0.9,
    maxHeight: SCREEN_HEIGHT * 0.7,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  helperHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  helperTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  helperClose: {
    fontSize: 24,
    color: colors.textSecondary,
  },
  helperContent: {
    padding: spacing.md,
  },
  helperField: {
    marginBottom: spacing.md,
  },
  helperFieldLabel: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  helperFieldValue: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.background,
    padding: spacing.sm,
    borderRadius: 8,
  },
  helperFieldText: {
    fontSize: 16,
    color: colors.text,
    flex: 1,
  },
  helperCopyButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: 6,
    marginLeft: spacing.sm,
  },
  helperCopyButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  helperCopied: {
    backgroundColor: colors.success || '#28a745',
  },
  helperSection: {
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  helperSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: spacing.md,
  },
  debugButton: {
    backgroundColor: '#6c757d',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 6,
    marginTop: spacing.sm,
  },
  debugButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  comparisonModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  comparisonModalContent: {
    flex: 1,
    backgroundColor: colors.background,
  },
  comparisonHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  comparisonTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  comparisonCloseButton: {
    padding: spacing.sm,
  },
  comparisonCloseButtonText: {
    fontSize: 24,
    color: colors.textSecondary,
  },
  comparisonScroll: {
    flex: 1,
  },
  comparisonScrollContent: {
    padding: spacing.md,
  },
  comparisonSection: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  comparisonSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: spacing.md,
  },
  comparisonRow: {
    marginBottom: spacing.md,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  comparisonFieldName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: spacing.xs,
  },
  comparisonValues: {
    marginTop: spacing.xs,
  },
  comparisonValueRow: {
    flexDirection: 'row',
    marginTop: spacing.xs,
  },
  comparisonLabel: {
    fontSize: 13,
    color: colors.textSecondary,
    width: 100,
  },
  comparisonValue: {
    fontSize: 13,
    color: colors.text,
    flex: 1,
  },
  comparisonMatch: {
    backgroundColor: '#d4edda',
    padding: spacing.xs,
    borderRadius: 4,
    marginTop: spacing.xs,
  },
  comparisonMatchText: {
    fontSize: 12,
    color: '#155724',
    fontWeight: '600',
  },
  comparisonMismatch: {
    backgroundColor: '#f8d7da',
    padding: spacing.xs,
    borderRadius: 4,
    marginTop: spacing.xs,
  },
  comparisonMismatchText: {
    fontSize: 12,
    color: '#721c24',
    fontWeight: '600',
  },
  comparisonPayloadScroll: {
    backgroundColor: '#f8f9fa',
    borderRadius: 4,
    padding: spacing.sm,
    maxHeight: 300,
  },
  comparisonPayload: {
    fontSize: 11,
    fontFamily: 'Courier',
    color: colors.text,
  },
  comparisonActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: spacing.md,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  comparisonRefreshButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 6,
  },
  comparisonRefreshButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  comparisonExportButton: {
    backgroundColor: '#6c757d',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 6,
  },
  comparisonExportButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  // Extended comparison styles for DataComparisonModal
  comparisonContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  comparisonHeaderLeft: {
    flex: 1,
  },
  comparisonSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 4,
  },
  comparisonContent: {
    flex: 1,
  },
  comparisonSummary: {
    backgroundColor: colors.background,
    borderRadius: 8,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  comparisonSummaryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.xs,
  },
  comparisonSummaryLabel: {
    fontSize: 14,
    color: colors.textSecondary,
    flex: 1,
  },
  comparisonSummaryValue: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  comparisonFieldItem: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: spacing.sm,
    marginBottom: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
  },
  comparisonFieldItemError: {
    borderColor: '#F44336',
    backgroundColor: '#FFF5F5',
  },
  comparisonFieldItemWarning: {
    borderColor: '#FF9800',
    backgroundColor: '#FFF8E1',
  },
  comparisonFieldHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  comparisonFieldStatus: {
    fontSize: 14,
    fontWeight: '600',
  },
  comparisonFieldSource: {
    fontSize: 13,
    color: colors.primary,
    flex: 1,
  },
  comparisonFieldTransform: {
    fontSize: 13,
    color: '#FF9800',
    flex: 1,
    fontStyle: 'italic',
  },
  comparisonFieldNotes: {
    marginTop: spacing.xs,
    padding: spacing.xs,
    backgroundColor: '#FFF8E1',
    borderRadius: 4,
  },
  comparisonFieldNotesText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  qrModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  qrModalContainer: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.xl,
    width: SCREEN_WIDTH * 0.9,
    maxWidth: 400,
  },
  qrModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  qrModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
  },
  qrCloseButton: {
    padding: spacing.xs,
  },
  qrCloseButtonText: {
    fontSize: 24,
    color: colors.textSecondary,
  },
  qrCodeContent: {
    alignItems: 'center',
  },
  qrCodeImage: {
    width: 250,
    height: 250,
    marginBottom: spacing.md,
  },
  qrHint: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  qrSubHint: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  qrInfo: {
    width: '100%',
    backgroundColor: colors.background,
    padding: spacing.md,
    borderRadius: 8,
    marginBottom: spacing.md,
  },
  qrInfoLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: spacing.sm,
  },
  qrInfoValue: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '600',
    marginTop: spacing.xs,
  },
  qrSaveAgainButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 8,
    width: '100%',
  },
  qrSaveAgainButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  languageNotification: {
    position: 'absolute',
    top: 60,
    left: spacing.md,
    right: spacing.md,
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    zIndex: 100,
  },
  languageNotificationContent: {
    flex: 1,
  },
  languageNotificationIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  languageNotificationTextContainer: {
    flex: 1,
  },
  languageNotificationTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.white,
    marginBottom: 2,
  },
  languageNotificationLanguage: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.white,
  },
  languageNotificationCheck: {
    fontSize: 24,
    color: colors.white,
    marginLeft: spacing.sm,
  },
  // Copy helper field styles
  fieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  fieldLeft: {
    flex: 1,
    marginRight: spacing.sm,
  },
  fieldLabel: {
    fontSize: 14,
    color: colors.text,
  },
  fieldLabelCn: {
    fontSize: 12,
    color: colors.lightText,
    marginTop: 2,
  },
  fieldValue: {
    fontSize: 12,
    color: colors.primary,
    marginTop: 2,
  },
  buttonGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  autoFillButton: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.primary,
    borderRadius: 4,
    marginRight: spacing.xs,
  },
  autoFillButtonActive: {
    backgroundColor: colors.success,
  },
  autoFillButtonText: {
    fontSize: 16,
    color: colors.white,
  },
  copyButton: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.border,
    borderRadius: 4,
  },
  copyButtonActive: {
    backgroundColor: colors.success,
  },
  copyButtonText: {
    fontSize: 14,
    color: colors.white,
  },
  // Cloudflare notification styles
  cloudflareReminder: {
    backgroundColor: colors.white,
    borderRadius: 12,
    marginHorizontal: spacing.md,
    marginBottom: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  cloudflareContent: {
    alignItems: 'center',
    paddingVertical: spacing.md,
  },
  cloudflareIconContainer: {
    marginBottom: spacing.md,
  },
  cloudflareIcon: {
    fontSize: 48,
  },
  cloudflareTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  cloudflareTextCn: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  cloudflareTextEn: {
    fontSize: 12,
    color: colors.lightText,
    textAlign: 'center',
  },
  // HelperModal styles
  modalContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
  },
  closeButton: {
    padding: spacing.xs,
  },
  closeButtonText: {
    fontSize: 16,
    color: colors.primary,
  },
  modalContent: {
    flex: 1,
    padding: spacing.md,
  },
  instructionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    padding: spacing.md,
    borderRadius: 8,
    marginBottom: spacing.md,
  },
  instructionIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  instructionText: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
  },
  section: {
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  stepBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    color: colors.white,
    textAlign: 'center',
    lineHeight: 28,
    fontSize: 14,
    fontWeight: '600',
    marginRight: spacing.sm,
    overflow: 'hidden',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  noteCard: {
    backgroundColor: '#FFF8E1',
    padding: spacing.md,
    borderRadius: 8,
    marginTop: spacing.md,
    marginBottom: spacing.md,
  },
  noteIcon: {
    fontSize: 20,
    marginBottom: spacing.xs,
  },
  noteContent: {
    flex: 1,
  },
  noteTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: spacing.xs,
  },
  noteText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  tipsCard: {
    backgroundColor: '#E8F5E9',
    padding: spacing.md,
    borderRadius: 8,
    marginBottom: spacing.md,
  },
  tipsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: spacing.xs,
  },
  tipsText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  bottomPadding: {
    height: 40,
  },
  // Floating action button styles
  cloudflareArrow: {
    fontSize: 12,
    color: colors.primary,
    marginLeft: spacing.xs,
  },
  floatingButtonsContainer: {
    position: 'absolute',
    bottom: spacing.lg,
    left: spacing.md,
    right: spacing.md,
    gap: spacing.sm,
  },
  floatingButtonPrimary: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  floatingButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  floatingButtonIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
    color: colors.white,
  },
  floatingButtonTextContainer: {
    flex: 1,
  },
  floatingButtonTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
  },
  floatingButtonSubtitle: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 2,
  },
  floatingButtonGlow: {
    position: 'absolute',
    top: -4,
    left: -4,
    right: -4,
    bottom: -4,
    borderRadius: 16,
    opacity: 0.3,
  },
  floatingButtonSecondary: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
});

export default styles;
