// @ts-nocheck

/**
 * Styles for TDACWebViewScreen
 *
 * Extracted styles for the TDAC WebView filling assistant screen
 */

import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography, spacing } from '../../theme';

const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    marginLeft: -spacing.sm,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  headerRight: {
    width: 40,
  },
  webView: {
    flex: 1,
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    zIndex: 30,
  },
  loadingBox: {
    alignItems: 'center',
    padding: spacing.xl,
    borderRadius: 20,
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
    borderWidth: 2,
    borderColor: colors.primary,
    minWidth: 200,
  },
  loadingText: {
    marginTop: spacing.md,
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  loadingSubText: {
    marginTop: spacing.xs,
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  cloudflareReminderOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    zIndex: 20,
  },
  cloudflareReminderBox: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.xl,
    marginHorizontal: spacing.lg,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  cloudflareReminderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  cloudflareReminderText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: spacing.xl,
  },
  cloudflareReminderButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    borderRadius: 8,
    minWidth: 120,
  },
  cloudflareReminderButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  visualMask: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    zIndex: 15,
  },
  helper: {
    position: 'absolute',
    bottom: spacing.md,
    right: spacing.md,
    backgroundColor: colors.primary,
    borderRadius: 28,
    padding: spacing.md,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  helperIcon: {
    fontSize: 24,
  },
  helperPanel: {
    position: 'absolute',
    bottom: 80,
    right: spacing.md,
    backgroundColor: colors.white,
    borderRadius: 12,
    width: SCREEN_WIDTH * 0.9,
    maxHeight: SCREEN_HEIGHT * 0.7,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  helperHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  helperTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  helperClose: {
    fontSize: 24,
    color: colors.textSecondary,
  },
  helperContent: {
    padding: spacing.md,
  },
  helperField: {
    marginBottom: spacing.md,
  },
  helperFieldLabel: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  helperFieldValue: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.background,
    padding: spacing.sm,
    borderRadius: 8,
  },
  helperFieldText: {
    fontSize: 16,
    color: colors.text,
    flex: 1,
  },
  helperCopyButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: 6,
    marginLeft: spacing.sm,
  },
  helperCopyButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  helperCopied: {
    backgroundColor: colors.success || '#28a745',
  },
  helperSection: {
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  helperSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: spacing.md,
  },
  debugButton: {
    backgroundColor: '#6c757d',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 6,
    marginTop: spacing.sm,
  },
  debugButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  comparisonModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  comparisonModalContent: {
    flex: 1,
    backgroundColor: colors.background,
  },
  comparisonHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  comparisonTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  comparisonCloseButton: {
    padding: spacing.sm,
  },
  comparisonCloseButtonText: {
    fontSize: 24,
    color: colors.textSecondary,
  },
  comparisonScroll: {
    flex: 1,
  },
  comparisonScrollContent: {
    padding: spacing.md,
  },
  comparisonSection: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  comparisonSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: spacing.md,
  },
  comparisonRow: {
    marginBottom: spacing.md,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  comparisonFieldName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: spacing.xs,
  },
  comparisonValues: {
    marginTop: spacing.xs,
  },
  comparisonValueRow: {
    flexDirection: 'row',
    marginTop: spacing.xs,
  },
  comparisonLabel: {
    fontSize: 13,
    color: colors.textSecondary,
    width: 100,
  },
  comparisonValue: {
    fontSize: 13,
    color: colors.text,
    flex: 1,
  },
  comparisonMatch: {
    backgroundColor: '#d4edda',
    padding: spacing.xs,
    borderRadius: 4,
    marginTop: spacing.xs,
  },
  comparisonMatchText: {
    fontSize: 12,
    color: '#155724',
    fontWeight: '600',
  },
  comparisonMismatch: {
    backgroundColor: '#f8d7da',
    padding: spacing.xs,
    borderRadius: 4,
    marginTop: spacing.xs,
  },
  comparisonMismatchText: {
    fontSize: 12,
    color: '#721c24',
    fontWeight: '600',
  },
  comparisonPayloadScroll: {
    backgroundColor: '#f8f9fa',
    borderRadius: 4,
    padding: spacing.sm,
    maxHeight: 300,
  },
  comparisonPayload: {
    fontSize: 11,
    fontFamily: 'Courier',
    color: colors.text,
  },
  comparisonActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: spacing.md,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  comparisonRefreshButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 6,
  },
  comparisonRefreshButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  comparisonExportButton: {
    backgroundColor: '#6c757d',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 6,
  },
  comparisonExportButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  qrModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  qrModalContainer: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.xl,
    width: SCREEN_WIDTH * 0.9,
    maxWidth: 400,
  },
  qrModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  qrModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
  },
  qrCloseButton: {
    padding: spacing.xs,
  },
  qrCloseButtonText: {
    fontSize: 24,
    color: colors.textSecondary,
  },
  qrCodeContent: {
    alignItems: 'center',
  },
  qrCodeImage: {
    width: 250,
    height: 250,
    marginBottom: spacing.md,
  },
  qrHint: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  qrSubHint: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  qrInfo: {
    width: '100%',
    backgroundColor: colors.background,
    padding: spacing.md,
    borderRadius: 8,
    marginBottom: spacing.md,
  },
  qrInfoLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: spacing.sm,
  },
  qrInfoValue: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '600',
    marginTop: spacing.xs,
  },
  qrSaveAgainButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 8,
    width: '100%',
  },
  qrSaveAgainButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  languageNotification: {
    position: 'absolute',
    top: 60,
    left: spacing.md,
    right: spacing.md,
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    zIndex: 100,
  },
  languageNotificationContent: {
    flex: 1,
  },
  languageNotificationTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.white,
    marginBottom: 2,
  },
  languageNotificationLanguage: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.white,
  },
  languageNotificationCheck: {
    fontSize: 24,
    color: colors.white,
    marginLeft: spacing.sm,
  },
});

export default styles;
