// @ts-nocheck

/**
 * Malaysia Labels Configuration
 * English/Chinese/Malay trilingual labels
 */

export const malaysiaLabels = {
  screenTitle: '马来西亚入境信息表',
  screenTitleEn: 'Malaysia Entry Information',
  passport: {
    title: '护照信息 - Passport - Pasport',
    subtitle: '请准确填写护照信息',
    icon: '📘',
    introIcon: '🛂',
    introText: '请确保所有信息与护照一致',
    fullName: '姓名 - Full Name - Nama Penuh',
    fullNameHelp: '按护照顺序填写',
    nationality: '国籍 - Nationality - Kewarganegaraan',
    nationalityHelp: '选择国籍',
    passportNo: '护照号 - Passport Number - Nombor Pasport',
    passportNoHelp: '输入护照号',
    visaNumber: '签证号 - Visa Number - Nombor Visa',
    visaNumberHelp: '如有签证请填写',
    dob: '出生日期 - Date of Birth - Tarikh Lahir',
    dobHelp: '选择出生日期',
    expiryDate: '有效期 - Expiry Date - Tarikh Luput',
    expiryDateHelp: '选择到期日',
    sex: '性别 - Gender - Jantina',
  },
  personalInfo: {
    title: '个人信息 - Personal Info - Maklumat Peribadi',
    subtitle: '联系方式和职业',
    icon: '👤',
    introIcon: '📋',
    introText: '海关需要您的联系方式',
    occupation: '职业 - Occupation - Pekerjaan',
    occupationHelp: '选择职业',
    occupationPlaceholder: '请选择',
    customOccupationLabel: '其他',
    customOccupationPlaceholder: '请说明',
    cityOfResidence: '城市 - City - Bandar',
    cityOfResidenceHelp: '居住城市',
    countryOfResidence: '国家 - Country - Negara',
    countryOfResidenceHelp: '居住国家',
    phoneLabel: '电话 - Phone - Telefon',
    phoneCodeLabel: '代码 - Code - Kod',
    phoneCodeHelp: '国家代码',
    phoneNumberLabel: '号码 - Number - Nombor',
    phoneNumberHelp: '电话号码',
    email: '邮箱 - Email - Emel',
    emailHelp: '邮箱地址',
    emailPlaceholder: 'example@email.com',
  },
  funds: {
    title: '资金证明 - Funds - Dana',
    subtitle: '旅游资金',
    icon: '💰',
    introIcon: '💵',
    introText: '马来西亚海关可能要求资金证明',
    addFundTitle: '添加资金',
    cash: '现金 - Cash',
    creditCard: '信用卡 - Credit Card',
    bankBalance: '银行存款 - Bank',
    travelersCheque: '支票 - Cheque',
    other: '其他 - Other',
    amount: '金额',
    currency: '币种',
    photo: '照片',
    hasPhoto: '已上传',
    noPhoto: '未上传',
    emptyTitle: '暂无资金',
    emptyMessage: '点击添加',
  },
  travelDetails: {
    title: '旅行详情 - Travel - Perjalanan',
    subtitle: '航班和住宿',
    icon: '✈️',
    introIcon: '✈️',
    introText: '海关需了解旅行计划',
    travelPurpose: '目的 - Purpose - Tujuan',
    travelPurposeHelp: '访问原因',
    travelPurposePlaceholder: '请选择',
    customTravelPurposeLabel: '其他',
    customTravelPurposePlaceholder: '请说明',
    recentStayCountry: '近30天访问国家',
    recentStayCountryHelp: '最近访问的国家',
    boardingCountry: '登机国 - Boarding',
    boardingCountryHelp: '登机国家',
    arrivalFlightNumber: '航班号 - Flight',
    arrivalFlightNumberHelp: '入境航班',
    arrivalFlightNumberPlaceholder: 'MH123',
    arrivalDate: '入境日期 - Arrival',
    arrivalDateHelp: '入境日期',
    flightTicketPhoto: '机票',
    uploadFlightTicket: '上传',
    departureFlightNumber: '离境航班 - Departure',
    departureFlightNumberHelp: '离境航班号',
    departureFlightNumberPlaceholder: 'MH456',
    departureDate: '离境日期 - Departure',
    departureDateHelp: '离境日期',
    departureFlightTicketPhoto: '返程机票',
    uploadDepartureFlightTicket: '上传',
    isTransitPassenger: '过境旅客？',
    transitYes: '是 - Yes',
    transitNo: '否 - No',
    accommodationType: '住宿类型 - Accommodation',
    accommodationTypeHelp: '选择住宿',
    customAccommodationType: '其他',
    province: '州 - State - Negeri',
    provinceHelp: '选择州',
    provincePlaceholder: '请选择',
    district: '区 - District - Daerah',
    districtHelp: '选择区',
    districtPlaceholder: '请选择',
    hotelAddress: '地址 - Address - Alamat',
    hotelAddressHelp: '完整地址',
    hotelAddressPlaceholder: '输入地址',
    hotelReservationPhoto: '预订单',
    uploadHotelReservation: '上传',
  },
  progress: { overallProgress: '进度', completed: '完成', remaining: '剩余', saveAndContinue: '保存', submit: '提交' },
  validation: { required: '必填', invalidEmail: '无效邮箱', invalidPassport: '无效护照', invalidPhone: '无效电话' },
  success: { saved: '已保存', submitted: '已提交' },
  errors: { saveFailed: '保存失败', loadFailed: '加载失败', submitFailed: '提交失败' },
};

export const malaysiaConfig = {
  passport: { showVisaNumber: true, genderOptions: [{ label: '男 - Male', value: 'M' }, { label: '女 - Female', value: 'F' }] },
  personalInfo: { uppercaseCity: true, uppercaseOccupation: true },
  funds: { fundTypes: ['cash', 'credit_card', 'bank_balance', 'travelers_cheque', 'other'], showPhotos: true },
  travelDetails: {
    showTravelPurpose: true, showRecentStayCountry: true, showBoardingCountry: true, showArrivalFlight: true, showDepartureFlight: true,
    showAccommodation: true, showFlightTicketPhoto: true, showDepartureFlightTicketPhoto: true, showTransitPassenger: true, showHotelReservationPhoto: true,
    locationDepth: 2, showPostalCode: false, purposeType: 'basic',
    accommodationOptions: [
      { label: '酒店 - Hotel', value: 'HOTEL' },
      { label: '旅馆 - Hostel', value: 'HOSTEL' },
      { label: '民宿 - Airbnb', value: 'AIRBNB' },
      { label: '朋友家 - Friend', value: 'FRIEND_FAMILY' },
      { label: '其他 - Other', value: 'OTHER' },
    ],
  },
};

export default { labels: malaysiaLabels, config: malaysiaConfig };
