/**
 * Singapore Labels Configuration  
 * English/Chinese (Simplified) bilingual labels
 */

export const singaporeLabels = {
  screenTitle: '新加坡入境信息表',
  screenTitleEn: 'Singapore Entry Information',

  passport: {
    title: '护照信息 - Passport Information',
    subtitle: '请准确填写护照上的信息',
    icon: '📘',
    introIcon: '🛂',
    introText: '请确保所有信息与您的护照完全一致',
    fullName: '护照上的姓名 - Full Name',
    fullNameHelp: '请按照护照上的顺序填写',
    nationality: '国籍 - Nationality',
    nationalityHelp: '选择您的国籍',
    passportNo: '护照号码 - Passport Number',
    passportNoHelp: '输入您的护照号码',
    visaNumber: '签证号码（可选）- Visa Number (Optional)',
    visaNumberHelp: '如有签证请填写',
    dob: '出生日期 - Date of Birth',
    dobHelp: '选择您的出生日期',
    expiryDate: '护照有效期 - Expiry Date',
    expiryDateHelp: '选择护照到期日期',
    sex: '性别 - Gender',
  },

  personalInfo: {
    title: '个人信息 - Personal Information',
    subtitle: '联系方式和职业信息',
    icon: '👤',
    introIcon: '📋',
    introText: '海关需要您的联系方式',
    occupation: '职业 - Occupation',
    occupationHelp: '选择您的职业',
    occupationPlaceholder: '请选择',
    customOccupationLabel: '其他职业 - Other',
    customOccupationPlaceholder: '请说明',
    cityOfResidence: '居住城市 - City',
    cityOfResidenceHelp: '填写您的居住城市',
    countryOfResidence: '居住国家 - Country',
    countryOfResidenceHelp: '选择您的居住国家',
    phoneLabel: '电话号码 - Phone',
    phoneCodeLabel: '国家代码 - Code',
    phoneCodeHelp: '选择国家代码',
    phoneNumberLabel: '电话号码 - Number',
    phoneNumberHelp: '输入电话号码',
    email: '电子邮箱 - Email',
    emailHelp: '输入邮箱地址',
    emailPlaceholder: 'example@email.com',
  },

  funds: {
    title: '资金证明 - Proof of Funds',
    subtitle: '旅游资金和支付方式',
    icon: '💰',
    introIcon: '💵',
    introText: '新加坡海关可能要求您出示足够的旅游资金证明',
    addFundTitle: '添加资金证明',
    cash: '现金 - Cash',
    creditCard: '信用卡 - Credit Card',
    bankBalance: '银行存款 - Bank Balance',
    travelersCheque: '旅行支票 - Cheque',
    other: '其他 - Other',
    amount: '金额 - Amount',
    currency: '币种 - Currency',
    photo: '照片 - Photo',
    hasPhoto: '已上传',
    noPhoto: '未上传',
    emptyTitle: '暂无资金证明',
    emptyMessage: '点击上方按钮添加',
  },

  travelDetails: {
    title: '旅行详情 - Travel Details',
    subtitle: '航班和住宿信息',
    icon: '✈️',
    introIcon: '✈️',
    introText: '海关需要了解您的旅行计划',
    travelPurpose: '访问目的 - Purpose',
    travelPurposeHelp: '选择访问原因',
    travelPurposePlaceholder: '请选择',
    customTravelPurposeLabel: '其他目的',
    customTravelPurposePlaceholder: '请说明',
    recentStayCountry: '近30天访问过的国家',
    recentStayCountryHelp: '选择最近访问的国家',
    boardingCountry: '登机国家 - Boarding Country',
    boardingCountryHelp: '选择登机国家',
    arrivalFlightNumber: '入境航班号 - Arrival Flight',
    arrivalFlightNumberHelp: '输入航班号',
    arrivalFlightNumberPlaceholder: '例如：SQ123',
    arrivalDate: '入境日期 - Arrival Date',
    arrivalDateHelp: '选择入境日期',
    flightTicketPhoto: '机票照片',
    uploadFlightTicket: '上传机票',
    departureFlightNumber: '离境航班号 - Departure Flight',
    departureFlightNumberHelp: '输入离境航班号',
    departureFlightNumberPlaceholder: '例如：SQ456',
    departureDate: '离境日期 - Departure Date',
    departureDateHelp: '选择离境日期',
    departureFlightTicketPhoto: '返程机票照片',
    uploadDepartureFlightTicket: '上传返程机票',
    isTransitPassenger: '是否为过境旅客？',
    transitYes: '是 - Yes',
    transitNo: '否 - No',
    accommodationType: '住宿类型 - Accommodation',
    accommodationTypeHelp: '选择住宿类型',
    customAccommodationType: '其他住宿类型',
    province: '区域 - Planning Area',
    provinceHelp: '选择区域',
    provincePlaceholder: '请选择区域',
    district: '街道 - Street',
    districtHelp: '选择街道',
    districtPlaceholder: '请选择街道',
    subDistrict: '邮编 - Postal',
    subDistrictHelp: '选择邮编',
    subDistrictPlaceholder: '请选择',
    postalCode: '邮政编码 - Postal Code',
    hotelAddress: '酒店地址 - Hotel Address',
    hotelAddressHelp: '输入完整地址',
    hotelAddressPlaceholder: '输入地址',
    hotelReservationPhoto: '酒店预订单',
    uploadHotelReservation: '上传预订单',
  },

  progress: {
    overallProgress: '总体进度',
    completed: '已完成',
    remaining: '剩余',
    saveAndContinue: '保存并继续',
    submit: '提交',
  },

  validation: {
    required: '此字段为必填项',
    invalidEmail: '请输入有效的电子邮箱',
    invalidPassport: '请输入有效的护照号码',
    invalidPhone: '请输入有效的电话号码',
  },

  success: { saved: '已保存', submitted: '已提交' },
  errors: { saveFailed: '保存失败', loadFailed: '加载失败', submitFailed: '提交失败' },
};

export const singaporeConfig = {
  passport: {
    showVisaNumber: true,
    genderOptions: [
      { label: '男性 - Male', value: 'M' },
      { label: '女性 - Female', value: 'F' },
    ],
  },
  personalInfo: {
    uppercaseCity: true,
    uppercaseOccupation: true,
  },
  funds: {
    fundTypes: ['cash', 'credit_card', 'bank_balance', 'travelers_cheque', 'other'],
    showPhotos: true,
  },
  travelDetails: {
    showTravelPurpose: true,
    showRecentStayCountry: true,
    showBoardingCountry: true,
    showArrivalFlight: true,
    showDepartureFlight: true,
    showAccommodation: true,
    showFlightTicketPhoto: true,
    showDepartureFlightTicketPhoto: true,
    showTransitPassenger: true,
    showHotelReservationPhoto: true,
    locationDepth: 1, // Singapore uses single-level (planning areas only)
    showPostalCode: true,
    purposeType: 'basic',
    accommodationOptions: [
      { label: '酒店 - Hotel', value: 'HOTEL' },
      { label: '旅馆 - Hostel', value: 'HOSTEL' },
      { label: '民宿 - Airbnb', value: 'AIRBNB' },
      { label: '朋友/亲戚家 - Friend/Family', value: 'FRIEND_FAMILY' },
      { label: '其他 - Other', value: 'OTHER' },
    ],
  },
};

export default { labels: singaporeLabels, config: singaporeConfig };
