import type { NavigatorScreenParams } from '@react-navigation/native';
import type { BottomTabScreenProps } from '@react-navigation/bottom-tabs';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';

export type MainTabParamList = {
  Home: undefined;
  History: undefined;
  Profile: undefined;
};

export type RootStackParamList = {
  Login: undefined;
  MainTabs: NavigatorScreenParams<MainTabParamList> | undefined;
  ScanPassport: undefined;
  SelectDestination: undefined;
  TravelInfo: undefined;
  Generating: undefined;
  Result: undefined;
  PresentToCustoms: undefined;
  PIKGuide: undefined;
  CopyWrite: undefined;
  TDACSelection: undefined;
  TDACWebView: undefined;
  TDACAPI: undefined;
  TDACHybrid: undefined;
  TDACFiles: undefined;
  SingaporeInfo: undefined;
  SingaporeRequirements: undefined;
  MalaysiaInfo: undefined;
  MalaysiaRequirements: undefined;
  MDACSelection: undefined;
  MDACGuide: undefined;
  MDACWebView: undefined;
  MalaysiaTravelInfo: undefined;
  MalaysiaEntryFlow: undefined;
  MalaysiaEntryGuide: undefined;
  MalaysiaEntryPackPreview: undefined;
  TaiwanInfo: undefined;
  TaiwanRequirements: undefined;
  TaiwanEntryFlow: undefined;
  TaiwanEntryPackPreview: undefined;
  TaiwanTravelInfo: undefined;
  TWArrivalSelection: undefined;
  TWArrivalGuide: undefined;
  TWArrivalWebView: undefined;
  HongKongInfo: undefined;
  HongKongRequirements: undefined;
  HongKongEntryFlow: undefined;
  HongKongEntryPackPreview: undefined;
  HongKongEntryGuide: undefined;
  HongkongTravelInfo: undefined;
  HDACSelection: undefined;
  HDACGuide: undefined;
  HDACWebView: undefined;
  KoreaInfo: undefined;
  KoreaRequirements: undefined;
  KoreaTravelInfo: undefined;
  KoreaEntryFlow: undefined;
  KoreaEntryGuide: undefined;
  KoreaEntryPackPreview: undefined;
  USAInfo: undefined;
  USARequirements: undefined;
  USTravelInfo: undefined;
  USAEntryFlow: undefined;
  USAEntryPackPreview: undefined;
  USAEntryGuide: undefined;
  SGArrivalSelection: undefined;
  SGArrivalGuide: undefined;
  SGArrivalWebView: undefined;
  AirportArrival: undefined;
  ImmigrationGuide: undefined;
  ThailandInteractiveImmigrationGuide: undefined;
  ImmigrationOfficerView: undefined;
  ThailandEntryQuestions: undefined;
  ThailandInfo: undefined;
  ThailandRequirements: undefined;
  ThailandEntryFlow: undefined;
  ThailandTravelInfo: undefined;
  ThailandEntryGuide: undefined;
  ThailandEntryPackPreview: undefined;
  VietnamInfo: undefined;
  VietnamRequirements: undefined;
  VietnamTravelInfo: undefined;
  VietnamEntryFlow: undefined;
  VietnamEntryGuide: undefined;
  VietnamEntryPackPreview: undefined;
  JapanInfo: undefined;
  JapanRequirements: undefined;
  JapanProcedures: undefined;
  JapanTravelInfo: undefined;
  JapanEntryFlow: undefined;
  JapanEntryGuide: undefined;
  JapanInteractiveImmigrationGuide: undefined;
  EntryInfoDetail: undefined;
  EntryPackPreview: undefined;
  EntryInfoHistory: undefined;
  NotificationSettings: undefined;
  NotificationLog: undefined;
  NotificationTest?: undefined;
  TDACDebug?: undefined;
  TamaguiTest?: undefined;
  ComponentShowcase?: undefined;
} & {
  [key: string]: Record<string, unknown> | undefined;
};

export type RootStackScreenProps<T extends keyof RootStackParamList> = NativeStackScreenProps<RootStackParamList, T>;
export type MainTabScreenProps<T extends keyof MainTabParamList> = BottomTabScreenProps<MainTabParamList, T>;

export type ScreenProps = RootStackScreenProps<keyof RootStackParamList>;

